spring:
    output:
        ansi:
            enabled: always
    application:
        name: ticketing
    datasource:
        url: jdbc:mysql://localhost:3306/ticketing?serverTimezone=UTC&CharacterEncoding=UTF-8
        username: root
        password: very_difficult_root_password
        hikari:
            maximum-pool-size: 30
            connection-timeout: 5000
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc.time_zone: UTC
                show_sql: true
    jackson:
        time-zone: UTC
logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: debug
