spring:
    config:
        activate:
            on-profile: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true

decorator:
    datasource:
        p6spy:
            enable-logging: true
            multiline: false
            logging: slf4j
            log-file: spy.log