spring:
    output:
        ansi:
            enabled: always
    application:
        name: ticketing
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 30
            connection-timeout: 5000
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
        properties:
            jakarta.persistence.lock.timeout: 10000
            hibernate:
                jdbc.time_zone: UTC
                lock.timeout: 10000
        open-in-view: false
    jackson:
        time-zone: UTC


logging:
    request-response:
        enabled: true
        preview-length: 200
        max-content-length: 524288  # 500KB in bytes


decorator:
    datasource:
        p6spy:
            enable-logging: true
            multiline: false
            logging: slf4j
            log-file: spy.log


management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
    prometheus:
        metrics:
            export:
                enabled: true


config:
    valid-occupied-duration: 5 # 5분
    jwt:
        secret: very_difficult_and_secure_secret_key_that_is_at_least_256_bits
    distributed-lock:
        acquire-timeout: 5000 # lock 획득까지 기다릴 시간; 5초
        lock-ttl: 10000 # distributed lock 의 만료 시간; 10초
    scheduler:
        enabled: true
        queue-fixed-rate: 60000 # 1분
        occupation-fixed-rate: 60000 # 1분
