spring:
    output:
        ansi:
            enabled: always
    application:
        name: ticketing
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 30
            connection-timeout: 5000
    jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: validate
        properties:
            jakarta.persistence.lock.timeout: 10000
            hibernate:
                jdbc.time_zone: UTC
                lock.timeout: 10000
        open-in-view: false
    jackson:
        time-zone: UTC


slack:
    webhook-url: https://hooks.slack.com/services/YOUR/WEBHOOK/URL


logging:
    request-response:
        enabled: true
        preview-length: 200
        max-content-length: 524288  # 500KB in bytes


decorator:
    datasource:
        p6spy:
            enable-logging: true
            multiline: false
            logging: slf4j
            log-file: spy.log


management:
    endpoints:
        web:
            exposure:
                include: health,info,prometheus
    prometheus:
        metrics:
            export:
                enabled: true


config:
    valid-occupied-duration: 5 # 5분
    jwt:
        secret: very_difficult_and_secure_secret_key_that_is_at_least_256_bits
    distributed-lock:
        acquire-timeout: 5000 # lock 획득까지 기다릴 시간; 5초
        lock-ttl: 10000 # distributed lock 의 만료 시간; 10초
    queue:
        token-ttl-in-seconds: 3600 # token 의 ttl 을 초 단위로; 3600 초
        max-count-to-move: 1400 # 활성화할 토큰 수
        batch-size-to-move-to-active: 500 # waiting token 에서 active token 으로 변경할 때 batch size
        active-rate: 10000 # 활성화 주기; 10 초
    scheduler:
        enabled: true
        occupation-fixed-rate: 60000 # 1분
    caching:
        ttl-hour: 3600000  # 1시간
        max-idle-time-half-hour: 1800000 # 30분
        ttl-ten-min: 600000  # 10분
        max-idle-time-half-ten-min: 300000  # 5분
