name: ticketing
services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile.local
        volumes:
            - ..:/app
            - ../.gradle:/root/.gradle
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=${DB_URL}
            - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
            - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
            - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
            - SPRING_DATA_REDIS_HOST=${REDIS_HOST}
            - SPRING_DATA_REDIS_PORT=${REDIS_PORT}
        command: ./gradlew bootRun
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
            kafka-broker:
                condition: service_started
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
            interval: 30s
            timeout: 10s
            retries: 5
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 2G
        networks:
            - backend

    db:
        image: mysql:8.0
        volumes:
            - mysql-data:/var/lib/mysql
            - ../sql:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 4G
                reservations:
                    cpus: '1'
                    memory: 2G
        networks:
            - backend

    redis:
        image: redis:6.2-alpine
        ports:
            - "6379:6379"
        command: redis-server --notify-keyspace-events KEA
        depends_on:
            db:
                condition: service_healthy
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2G
                reservations:
                    cpus: '1'
                    memory: 1G
        networks:
            - backend

    kafka-controller:
        image: apache/kafka:3.8.0
        environment:
            KAFKA_NODE_ID: 1
            KAFKA_PROCESS_ROLES: 'controller'
            KAFKA_LISTENERS: 'CONTROLLER://:9093'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT'
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller:9093'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
        volumes:
            - kafka-controller-data:/var/lib/kafka
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3
            resources:
                limits:
                    cpus: '0.50'
                    memory: 512M
        networks:
            - backend

    kafka-broker:
        image: apache/kafka:3.8.0
        ports:
            - "9092:9092"
        environment:
            KAFKA_NODE_ID: 2
            KAFKA_PROCESS_ROLES: 'broker'
            KAFKA_LISTENERS: 'PLAINTEXT://:9092'
            KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-broker:9092'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
            KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
            KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-controller:9093'
            KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        depends_on:
            kafka-controller:
                condition: service_started
        volumes:
            - kafka-broker-data:/var/lib/kafka
        deploy:
            restart_policy:
                condition: on-failure
                max_attempts: 3
            resources:
                limits:
                    cpus: '1.00'
                    memory: 1G
        networks:
            - backend

    mysql-exporter:
        image: prom/mysqld-exporter:v0.15.1
        volumes:
            - ./my.cnf:/etc/mysqld-exporter/.my.cnf
        ports:
            - "9104:9104"
        environment:
            - DATA_SOURCE_NAME=${DB_USERNAME}:${DB_PASSWORD}@(db:3306)/
        command:
            - '--config.my-cnf=/etc/mysqld-exporter/.my.cnf'
        depends_on:
            db:
                condition: service_healthy
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
                reservations:
                    cpus: '0.5'
                    memory: 256M
        networks:
            - backend

    prometheus:
        image: prom/prometheus:v2.53.1
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus-data:/prometheus
        ports:
            - "9090:9090"
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--enable-feature=remote-write-receiver'
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 2G
                reservations:
                    cpus: '1'
                    memory: 1G
        networks:
            - backend

    grafana:
        image: grafana/grafana:11.1.1
        volumes:
            - grafana-data:/var/lib/grafana
        ports:
            - "3000:3000"
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
        depends_on:
            - prometheus
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 1G
                reservations:
                    cpus: '1'
                    memory: 512M
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    mysql-data:
    prometheus-data:
    grafana-data:
    kafka-controller-data:
    kafka-broker-data: