global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'spring-boot-app'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ['app:8080']
      relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'spring-boot-app'

    - job_name: 'mysql'
      static_configs:
          - targets: ['mysql-exporter:9104']
      relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'mysql'

    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
      relabel_configs:
          - source_labels: [__address__]
            target_label: instance
            replacement: 'prometheus'
